package com.abk.kernel.ui.screens.miuix

import com.abk.kernel.BuildConfig

data class OpenSourceNotice(
    val name: String,
    val license: String,
    val source: String,
    val url: String? = null
)

data class OpenSourceNoticeGroup(
    val titleRes: Int,
    val items: List<OpenSourceNotice>
)

private fun sourceRepoUrl(): String = "https://github.com/${BuildConfig.SOURCE_REPO_OWNER}/${BuildConfig.SOURCE_REPO_NAME}"

fun openSourceNoticeGroups(): List<OpenSourceNoticeGroup> = listOf(
    OpenSourceNoticeGroup(
        com.abk.kernel.R.string.settings_license_group_repository,
        listOf(
            OpenSourceNotice("AnyBase Kernel", "GPL-3.0", "LICENSE", sourceRepoUrl()),
            OpenSourceNotice("ABK Control native bridge", "GPL-2.0", "app/src/main/cpp/uapi/abk_control.h"),
            OpenSourceNotice("xingguang DDK module", "GPL", "ddk/xingguang-ddk/xingguang_ddk.c"),
            OpenSourceNotice("DDK kernel API patch", "GPL-2.0", "ddk/patches/xingguang-ddk/0001-xingguang-ddk-api.patch"),
            OpenSourceNotice("ZRAM LZ4 kernel glue", "GPL-2.0-only", "zram/lz4/Makefile")
        )
    ),
    OpenSourceNoticeGroup(
        com.abk.kernel.R.string.settings_license_group_upstream,
        listOf(
            OpenSourceNotice("zzh20188/GKI_KernelSU_SUSFS", "Upstream repository license", "BuildConfig.UPSTREAM_REPO_URL", BuildConfig.UPSTREAM_REPO_URL),
            OpenSourceNotice("WildKernels/GKI_KernelSU_SUSFS", "Upstream repository license", "BuildConfig.TOP_LEVEL_REPO_URL", BuildConfig.TOP_LEVEL_REPO_URL),
            OpenSourceNotice("CodeLinaro CLO LA", "Top-level upstream project licenses", "OnePlus manifest upstream", "https://git.codelinaro.org/clo/la"),
            OpenSourceNotice("OnePlusOSS/kernel_manifest", "Upstream repository license / no SPDX detected", "OnePlus manifest parent", "https://github.com/OnePlusOSS/kernel_manifest"),
            OpenSourceNotice("Xiaomichael/kernel_manifest", "Upstream repository license / no SPDX detected", "OnePlus manifest branch source", "https://github.com/Xiaomichael/kernel_manifest"),
            OpenSourceNotice("Xiaomichael/kernel_patches", "Upstream repository license / no SPDX detected", "OnePlus patch source", "https://github.com/Xiaomichael/kernel_patches"),
            OpenSourceNotice("KernelSU", "GPL-3.0", "workflow setup.sh source", "https://github.com/tiann/KernelSU"),
            OpenSourceNotice("KernelSU Next", "GPL-3.0", "workflow setup.sh source", "https://github.com/KernelSU-Next/KernelSU-Next"),
            OpenSourceNotice("SukiSU Ultra", "GPL-3.0", "kernel setup, ksud, android_bootimg", "https://github.com/SukiSU-Ultra/SukiSU-Ultra"),
            OpenSourceNotice("ReSukiSU", "GPL-3.0", "workflow setup.sh source", "https://github.com/ReSukiSU/ReSukiSU"),
            OpenSourceNotice("SUSFS", "GPL-2.0", "kernel patches and module integration", "https://gitlab.com/simonpunk/susfs4ksu"),
            OpenSourceNotice("ShirkNeko/susfs4ksu", "GPL-2.0", "GitHub mirror / patch source", "https://github.com/ShirkNeko/susfs4ksu"),
            OpenSourceNotice("SukiSU_patch", "GPL-2.0", "workflow patch source", "https://github.com/ShirkNeko/SukiSU_patch"),
            OpenSourceNotice("AnyKernel3", "GPL-2.0", "flashable kernel packaging", "https://github.com/WildKernels/AnyKernel3"),
            OpenSourceNotice("Xiaomichael/AnyKernel3", "Upstream repository license / NOASSERTION", "OnePlus flashable packaging source", "https://github.com/Xiaomichael/AnyKernel3"),
            OpenSourceNotice("WildKernels/kernel_patches", "GPL-2.0", "NTsync, IPSet, BBR and related patches", "https://github.com/WildKernels/kernel_patches"),
            OpenSourceNotice("cctv18/susfs4oki", "GPL-3.0", "OnePlus/OPPO/Realme SUSFS patch source", "https://github.com/cctv18/susfs4oki"),
            OpenSourceNotice("SukiSU_KernelPatch_patch", "Upstream repository license", "KPM patch source", "https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch"),
            OpenSourceNotice("Action-Build", "Upstream repository license", "workflow integration", "https://github.com/Numbersf/Action-Build"),
            OpenSourceNotice("sidex15/susfs4ksu-module", "Upstream repository license", "SUSFS module build source", "https://github.com/sidex15/susfs4ksu-module"),
            OpenSourceNotice("LineageOS GCC prebuilts", "GPL-family toolchain notices", "workflow toolchain source", "https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-6.4.1"),
            OpenSourceNotice("Baseband Guard", "Upstream repository license", "workflow setup source", "https://github.com/vc-teahouse/Baseband-guard"),
            OpenSourceNotice("Re-Kernel", "Upstream repository license", "workflow patch source", "https://github.com/Sakion-Team/Re-Kernel"),
            OpenSourceNotice("Droidspaces-OSS", "Upstream repository license", "virtualization support patches", "https://github.com/ravindu644/Droidspaces-OSS"),
            OpenSourceNotice("ABK_repo module catalog", "Upstream repository license", "official module catalog", "https://github.com/xingguangcuican6666/ABK_repo")
        )
    ),
    OpenSourceNoticeGroup(
        com.abk.kernel.R.string.settings_license_group_embedded,
        listOf(
            OpenSourceNotice("LZ4", "BSD-2-Clause", "zram/lz4 and zram/include/linux/lz4.h", "https://github.com/lz4/lz4"),
            OpenSourceNotice("AOSP kernel/common", "GPL-2.0 WITH Linux-syscall-note and AOSP notices", "android.googlesource.com/kernel/common", "https://android.googlesource.com/kernel/common"),
            OpenSourceNotice("AOSP kernel manifest", "AOSP project notices", "android.googlesource.com/kernel/manifest", "https://android.googlesource.com/kernel/manifest"),
            OpenSourceNotice("AOSP mkbootimg", "Apache-2.0", "android.googlesource.com/platform/system/tools/mkbootimg", "https://android.googlesource.com/platform/system/tools/mkbootimg"),
            OpenSourceNotice("AOSP kernel build-tools", "AOSP project notices", "android.googlesource.com/kernel/prebuilts/build-tools", "https://android.googlesource.com/kernel/prebuilts/build-tools"),
            OpenSourceNotice("Android GKI certified boot images", "Android image distribution terms", "dl.google.com/android/gki"),
            OpenSourceNotice("Android command line tools", "Android SDK License", "Dockerfile.test", "https://developer.android.com/studio")
        )
    ),
    OpenSourceNoticeGroup(
        com.abk.kernel.R.string.settings_license_group_android,
        androidDependencyNotices()
    ),
    OpenSourceNoticeGroup(
        com.abk.kernel.R.string.settings_license_group_web,
        webDependencyNotices()
    )
)

private fun androidDependencyNotices(): List<OpenSourceNotice> = listOf(
    OpenSourceNotice("Android Gradle Plugin 9.1.1", "Apache-2.0", "com.android.application"),
    OpenSourceNotice("Kotlin Gradle/Compose plugin 2.3.21", "Apache-2.0", "org.jetbrains.kotlin.plugin.compose"),
    OpenSourceNotice("androidx.core:core-ktx 1.15.0", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.lifecycle:lifecycle-runtime-ktx 2.8.7", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.lifecycle:lifecycle-viewmodel-compose 2.8.7", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.activity:activity-compose 1.9.3", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.compose:compose-bom 2026.05.00", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.compose.ui:ui", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.compose.ui:ui-graphics", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.compose.ui:ui-tooling-preview", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.compose.material3:material3 1.5.0-alpha19", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.compose.material:material-icons-extended", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("com.google.android.material:material 1.12.0", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("androidx.navigation:navigation-compose 2.8.5", "Apache-2.0", "Gradle direct dependency"),
    OpenSourceNotice("Retrofit 2.11.0", "Apache-2.0", "com.squareup.retrofit2:retrofit"),
    OpenSourceNotice("Retrofit Gson converter 2.11.0", "Apache-2.0", "com.squareup.retrofit2:converter-gson"),
    OpenSourceNotice("OkHttp 4.12.0", "Apache-2.0", "com.squareup.okhttp3:okhttp"),
    OpenSourceNotice("OkHttp logging-interceptor 4.12.0", "Apache-2.0", "com.squareup.okhttp3:logging-interceptor"),
    OpenSourceNotice("Gson 2.11.0", "Apache-2.0", "com.google.code.gson:gson"),
    OpenSourceNotice("kotlinx-serialization-json 1.7.3", "Apache-2.0", "org.jetbrains.kotlinx:kotlinx-serialization-json"),
    OpenSourceNotice("libsu core 5.2.2", "Apache-2.0", "com.github.topjohnwu.libsu:core"),
    OpenSourceNotice("libsu io 5.2.2", "Apache-2.0", "com.github.topjohnwu.libsu:io"),
    OpenSourceNotice("Coil Compose 2.7.0", "Apache-2.0", "io.coil-kt:coil-compose"),
    OpenSourceNotice("WorkManager runtime-ktx 2.10.0", "Apache-2.0", "androidx.work:work-runtime-ktx"),
    OpenSourceNotice("DataStore preferences 1.1.2", "Apache-2.0", "androidx.datastore:datastore-preferences"),
    OpenSourceNotice("JUnit 4.13.2", "EPL-1.0", "testImplementation"),
    OpenSourceNotice("AndroidX Test JUnit 1.2.1", "Apache-2.0", "androidTestImplementation"),
    OpenSourceNotice("Espresso Core 3.6.1", "Apache-2.0", "androidTestImplementation")
)

private fun webDependencyNotices(): List<OpenSourceNotice> = listOf(
    OpenSourceNotice("@discoveryjs/json-ext 0.6.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@jridgewell/gen-mapping 0.3.13", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@jridgewell/resolve-uri 3.1.2", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@jridgewell/source-map 0.3.11", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@jridgewell/sourcemap-codec 1.5.5", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@jridgewell/trace-mapping 0.3.31", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@parcel/watcher 2.5.6 and platform packages", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@types/eslint 9.6.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@types/eslint-scope 3.7.7", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@types/estree 1.0.8", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@types/json-schema 7.0.15", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@types/node 25.3.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@webassemblyjs/* 1.13.2-1.14.1", "MIT / Apache-2.0", "web/package-lock.json"),
    OpenSourceNotice("@webpack-cli/* 3.0.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("@xtuc/ieee754 1.2.0", "BSD-3-Clause", "web/package-lock.json"),
    OpenSourceNotice("@xtuc/long 4.2.2", "Apache-2.0", "web/package-lock.json"),
    OpenSourceNotice("acorn 8.16.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("acorn-import-phases 1.0.4", "MIT", "web/package-lock.json"),
    OpenSourceNotice("ajv 8.18.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("ajv-formats 2.1.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("ajv-keywords 5.1.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("baseline-browser-mapping 2.10.0", "Apache-2.0", "web/package-lock.json"),
    OpenSourceNotice("browserslist 4.28.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("buffer-from 1.1.2", "MIT", "web/package-lock.json"),
    OpenSourceNotice("caniuse-lite 1.0.30001776", "CC-BY-4.0", "web/package-lock.json"),
    OpenSourceNotice("chokidar 4.0.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("chrome-trace-event 1.0.4", "MIT", "web/package-lock.json"),
    OpenSourceNotice("clone-deep 4.0.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("colorette 2.0.20", "MIT", "web/package-lock.json"),
    OpenSourceNotice("commander 2.20.3 / 12.1.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("cross-spawn 7.0.6", "MIT", "web/package-lock.json"),
    OpenSourceNotice("css-loader 7.1.4", "MIT", "web/package-lock.json"),
    OpenSourceNotice("cssesc 3.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("detect-libc 2.1.2", "Apache-2.0", "web/package-lock.json"),
    OpenSourceNotice("electron-to-chromium 1.5.307", "ISC", "web/package-lock.json"),
    OpenSourceNotice("enhanced-resolve 5.20.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("envinfo 7.21.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("es-module-lexer 2.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("escalade 3.2.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("eslint-scope 5.1.1", "BSD-2-Clause", "web/package-lock.json"),
    OpenSourceNotice("esrecurse 4.3.0", "BSD-2-Clause", "web/package-lock.json"),
    OpenSourceNotice("estraverse 4.3.0 / 5.3.0", "BSD-2-Clause", "web/package-lock.json"),
    OpenSourceNotice("events 3.3.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("fast-deep-equal 3.1.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("fast-uri 3.1.0", "BSD-3-Clause", "web/package-lock.json"),
    OpenSourceNotice("fastest-levenshtein 1.0.16", "MIT", "web/package-lock.json"),
    OpenSourceNotice("find-up 4.1.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("flat 5.0.2", "BSD-3-Clause", "web/package-lock.json"),
    OpenSourceNotice("function-bind 1.1.2", "MIT", "web/package-lock.json"),
    OpenSourceNotice("glob-to-regexp 0.4.1", "BSD-2-Clause", "web/package-lock.json"),
    OpenSourceNotice("graceful-fs 4.2.11", "ISC", "web/package-lock.json"),
    OpenSourceNotice("has-flag 4.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("hasown 2.0.2", "MIT", "web/package-lock.json"),
    OpenSourceNotice("icss-utils 5.1.0", "ISC", "web/package-lock.json"),
    OpenSourceNotice("immutable 5.1.5", "MIT", "web/package-lock.json"),
    OpenSourceNotice("import-local 3.2.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("interpret 3.1.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("is-core-module 2.16.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("is-extglob 2.1.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("is-glob 4.0.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("is-plain-object 2.0.4", "MIT", "web/package-lock.json"),
    OpenSourceNotice("isexe 2.0.0", "ISC", "web/package-lock.json"),
    OpenSourceNotice("isobject 3.0.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("jest-worker 27.5.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("json-parse-even-better-errors 2.3.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("json-schema-traverse 1.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("kind-of 6.0.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("loader-runner 4.3.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("locate-path 5.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("merge-stream 2.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("mime-db 1.52.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("mime-types 2.1.35", "MIT", "web/package-lock.json"),
    OpenSourceNotice("mini-css-extract-plugin 2.10.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("nanoid 3.3.11", "MIT", "web/package-lock.json"),
    OpenSourceNotice("neo-async 2.6.2", "MIT", "web/package-lock.json"),
    OpenSourceNotice("node-addon-api 7.1.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("node-releases 2.0.36", "MIT", "web/package-lock.json"),
    OpenSourceNotice("p-limit / p-locate / p-try", "MIT", "web/package-lock.json"),
    OpenSourceNotice("path-exists / path-key / path-parse", "MIT", "web/package-lock.json"),
    OpenSourceNotice("picocolors 1.1.1", "ISC", "web/package-lock.json"),
    OpenSourceNotice("picomatch 4.0.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("pkg-dir 4.2.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("postcss 8.5.8", "MIT", "web/package-lock.json"),
    OpenSourceNotice("postcss-modules-*", "ISC / MIT", "web/package-lock.json"),
    OpenSourceNotice("postcss-selector-parser 7.1.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("postcss-value-parser 4.2.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("readdirp 4.1.2", "MIT", "web/package-lock.json"),
    OpenSourceNotice("rechoir 0.8.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("require-from-string 2.0.2", "MIT", "web/package-lock.json"),
    OpenSourceNotice("resolve 1.22.11", "MIT", "web/package-lock.json"),
    OpenSourceNotice("resolve-cwd 3.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("resolve-from 5.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("sass 1.97.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("sass-loader 16.0.5", "MIT", "web/package-lock.json"),
    OpenSourceNotice("schema-utils 4.3.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("semver 7.7.3", "ISC", "web/package-lock.json"),
    OpenSourceNotice("serialize-javascript 6.0.2", "BSD-3-Clause", "web/package-lock.json"),
    OpenSourceNotice("shallow-clone 3.0.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("shebang-command / shebang-regex", "MIT", "web/package-lock.json"),
    OpenSourceNotice("source-map 0.6.1", "BSD-3-Clause", "web/package-lock.json"),
    OpenSourceNotice("source-map-js 1.2.1", "BSD-3-Clause", "web/package-lock.json"),
    OpenSourceNotice("source-map-support 0.5.21", "MIT", "web/package-lock.json"),
    OpenSourceNotice("style-loader 4.0.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("supports-color 8.1.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("tapable 2.3.0", "MIT", "web/package-lock.json"),
    OpenSourceNotice("terser 5.44.1", "BSD-2-Clause", "web/package-lock.json"),
    OpenSourceNotice("terser-webpack-plugin 5.3.14", "MIT", "web/package-lock.json"),
    OpenSourceNotice("update-browserslist-db 1.1.5", "MIT", "web/package-lock.json"),
    OpenSourceNotice("uri-js 4.4.1", "BSD-2-Clause", "web/package-lock.json"),
    OpenSourceNotice("watchpack 2.4.4", "MIT", "web/package-lock.json"),
    OpenSourceNotice("webpack 5.102.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("webpack-cli 6.0.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("webpack-merge 6.0.1", "MIT", "web/package-lock.json"),
    OpenSourceNotice("webpack-sources 3.2.3", "MIT", "web/package-lock.json"),
    OpenSourceNotice("which 2.0.2", "ISC", "web/package-lock.json"),
    OpenSourceNotice("wildcard 2.0.1", "MIT", "web/package-lock.json")
)
